name: cicdtest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Print AWS Access Key ID
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: echo $AWS_ACCESS_KEY_ID

      - name: Print AWS Secret Access Key
        run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
